.\" Manpage for xfsudo.
.\" Contact aaditya_gnulinux@zoho.com.

.TH man 8 "10 May 2015" "0.6" "xfsudo man page"

.SH NAME
xfsudo \- run graphical applications with root priviliges using sudo.

.SH SYNOPSIS
.nf
xfsudo [program]
xfsu [program]
.fn

.SH DESCRIPTION
xfsudo runs graphical applications with root priviliges using sudo.
Zenity is used to display the dialog boxes.

By default it runs in sudo mode, ie, runs program with root priviliges,
but with user's environment variables.

To run instead with root's environment variables, it can be called as
xfsu instead of xfsudo.

.SH OPTIONS
The xfsudo command does not take any options. 
Only the program to be executed and its options are specified.

.SH EXAMPLES
.nf
xfsudo thunar
xfsudo thunar /etc	# opens the /etc directory in thunar with root priviliges
xfsu thunar		# runs thunar with root's environment variables

.fn
.SH SEE ALSO
sudo(8), visudo(8)
